version: '3.8'

services:
  todo:
      build: ./
      command: ./todo
      ports:
        - 8000:8000
      depends_on:
        - db
      environment:
        - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
